version: 2

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    groups:
      github-actions:
        patterns:
          - "*"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/"
    versioning-strategy: "increase"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
  - package-ecosystem: "pip"
    directory: "/"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    schedule:
      interval: "weekly"
