from typing import Any
from os import PathLike

class SqlQuery:
    query: str
    params: list[str]

class Expr:
    @staticmethod
    def from_path(path: PathLike) -> Expr: ...
    def __init__(self, cql2: str | dict[str, Any]) -> None: ...
    def to_json(self) -> dict[str, Any]: ...
    def to_text(self) -> str: ...
    def to_sql(self) -> SqlQuery: ...
